global:
  scrape_interval: 5s

#  external_labels:
#    monitor: "hw-backend"

rule_files:

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "backend"
    static_configs:
      - targets: ["hw-backend:8080"]

